CREATE TABLE IF NOT EXISTS nfs(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  img TEXT NOT NULL,
  register_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  emit_date TIMESTAMP NOT NULL,
  description TEXT NOT NULL,
  name VAR_CHAR(30) NOT NULL,
  total FLOAT NOT NULL
);
